# Generated by Django 2.0.5 on 2018-06-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_qa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='bounce_back',
        ),
        migrations.AddField(
            model_name='contact',
            name='sourced_by',
            field=models.CharField(default='username', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('HA_CONTACT', 'HA_Contact'), ('HR_CONTACT', 'HR-Contact')], max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listed',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source_type',
            field=models.CharField(default='TQR-India-Lead', max_length=255),
        ),
    ]
