# Generated by Django 2.0.5 on 2018-06-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_qa_app', '0002_auto_20180601_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='doNotEmail',
            field=models.BooleanField(default=False),
        ),
    ]
