# Generated by Django 2.0.5 on 2018-06-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_qa_app', '0004_auto_20180608_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='listed',
            field=models.BooleanField(default=False),
        ),
    ]
