# Generated by Django 2.0.5 on 2018-06-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_qa_app', '0010_auto_20180613_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('OTHERS', 'Others'), ('COMPANY_WEBSITE', 'Company Website')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
