# Generated by Django 2.0.6 on 2018-06-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_qa_app', '0012_auto_20180614_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='other_information',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('OTHERS', 'Others'), ('LINKEDIN', 'LinkedIn'), ('COMPANY_WEBSITE', 'Company Website')], max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sourced_by',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
